name: Brain Games CI
on:
  push:
    branches: [ master ]

jobs:
  run_linter:
     name: Run linter
     runs-on: ubuntu-latest
     steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v1
          with:
            python-version: 3.8
        - uses: Gr1N/setup-poetry@v4
        - run: poetry --version
        - name: Run linter
        - run: make lint
       
