name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - uses: Gr1N/setup-poetry@v4
        with:
          poetry-version: 1.1.6
      - run: poetry --version
      - run: make install
      - run: make lint
